---
- name: Pull and deploy Face Recognition system
  hosts: localhost
  connection: local
  become: true
  vars:
    project_dir: "/home/subha/SPE_Final_project"
    image_base: "substobeme/spe_project"

  tasks:
    - name: Pull training image
      shell: docker pull {{ image_base }}:training

    - name: Pull recognition image
      shell: docker pull {{ image_base }}:recognition

    - name: Pull frontend image
      shell: docker pull {{ image_base }}:frontend

    - name: Ensure run.sh is executable
      file:
        path: "{{ project_dir }}/run.sh"
        mode: '0755'
        state: file

    - name: Run the deployment script
      shell: ./run.sh 2>&1 | tee run_output.log
      args:
        chdir: "{{ project_dir }}"
      register: run_output
      environment:
        TERM: xterm
        DISPLAY: "{{ lookup('env', 'DISPLAY') | default(':0') }}"

    - name: Show script output
      debug:
        var: run_output.stdout_lines
