---
- name: Local deployment of face recognition system using run.sh
  hosts: localhost
  connection: local
  become: true
  vars:
    project_dir: "/home/subha/SPE_Final_project"

  tasks:
    - name: Check if run.sh script exists
      stat:
        path: "{{ project_dir }}/run.sh"
      register: run_script

    - name: Fail if run.sh script is not found
      fail:
        msg: "run.sh script not found in {{ project_dir }}. Please ensure the script is present."
      when: not run_script.stat.exists

    - name: Ensure run.sh is executable
      file:
        path: "{{ project_dir }}/run.sh"
        mode: '0755'
        state: file

    - name: Execute the run.sh script
      shell: ./run.sh
      args:
        chdir: "{{ project_dir }}"
