- name: Deploy Face Recognition system using run.sh
  hosts: localhost
  connection: local
  become: true
  vars:
    project_dir: "/home/subha/SPE_Final_project"
    display_var: ":0"
  roles:
    - git_clone
    - setup_x11
    - check_run_script
    - run_deployment
