---
- name: Deploy Face Recognition system using run.sh
  hosts: localhost
  connection: local
  become: false
  vars:
    project_dir: "/home/subha/SPE_Final_project"
    display_var: "{{ lookup('env', 'DISPLAY') | default(':0') }}"
  
  tasks:
    - name: Pull all required Docker images (optional, speeds up run.sh)
      shell: |
        docker pull substobeme/spe_project:training
        docker pull substobeme/spe_project:recognition
        docker pull substobeme/spe_project:frontend

    - name: Check if run.sh exists
      stat:
        path: "{{ project_dir }}/run.sh"
      register: run_script

    - name: Fail if run.sh is missing
      fail:
        msg: "run.sh script not found at {{ project_dir }}/run.sh"
      when: not run_script.stat.exists

    - name: Ensure run.sh is executable
      file:
        path: "{{ project_dir }}/run.sh"
        mode: '0755'

    - name: Run deployment script run.sh with environment
      shell: ./run.sh 2>&1 | tee run_output.log
      args:
        chdir: "{{ project_dir }}"
      environment:
        TERM: xterm
        DISPLAY: "{{ display_var }}"
      register: run_output

    - name: Show run.sh output
      debug:
        var: run_output.stdout_lines
