---
- name: Deploy Face Recognition system using run.sh
  hosts: localhost
  connection: local
  become: true
  vars:
    project_dir: "/home/subha/SPE_Final_project"
    display_var: "{{ lookup('env', 'DISPLAY') | default(':0') }}"
  tasks:
    - name: Print DISPLAY environment variable (debugging)
      debug:
        msg: "DISPLAY is set to {{ display_var }}"
    - name: Grant X11 permissions for Docker
      shell: xhost +local:docker
      when: ansible_facts['env']['DISPLAY'] is defined
    - name: Pull all required Docker images (optional)
      shell: |
        docker pull substobeme/spe_project:training || true
        docker pull substobeme/spe_project:recognition || true
        docker pull substobeme/spe_project:frontend || true
    - name: Check if run.sh exists
      stat:
        path: "{{ project_dir }}/run.sh"
      register: run_script
    - name: Fail if run.sh is missing
      fail:
        msg: "run.sh script not found at {{ project_dir }}/run.sh"
      when: not run_script.stat.exists
    - name: Ensure run.sh is executable
      file:
        path: "{{ project_dir }}/run.sh"
        mode: '0755'
    - name: Run deployment script run.sh with Qt and display environment
      shell: ./run.sh 2>&1 | tee run_output.log
      args:
        chdir: "{{ project_dir }}"
      environment:
        DISPLAY: "{{ display_var }}"
        TERM: xterm
        # Qt environment variables to fix XCB issues
        QT_QPA_PLATFORM: "offscreen"
        QT_X11_NO_MITSHM: "1"
        QT_PLUGIN_PATH: "/usr/local/lib/python3.9/site-packages/cv2/qt/plugins"
        QT_QPA_PLATFORM_PLUGIN_PATH: "/usr/local/lib/python3.9/site-packages/cv2/qt/plugins"
        # OpenCV environment variables
        OPENCV_VIDEOIO_PRIORITY_V4L2: "0"
      register: run_output
    - name: Show run.sh output
      debug:
        var: run_output.stdout_lines
