version: '3.8'

services:
  training:
    container_name: training
    image: substobeme/spe_project:training
    volumes:
      - ./data:/app/data
      - ./models:/app/models 
    command: python train_service.py

  recognition:
    container_name: recognition
    image: substobeme/spe_project:recognition
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./db:/app/db
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/${USER}/.Xauthority:/root/.Xauthority:rw
    depends_on:
      - training
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
      - QT_QPA_PLATFORM=xcb
      - QT_PLUGIN_PATH=/usr/local/lib/python3.9/site-packages/cv2/qt/plugins
      - QT_QPA_PLATFORM_PLUGIN_PATH=/usr/local/lib/python3.9/site-packages/cv2/qt/plugins
      - OPENCV_VIDEOIO_PRIORITY_V4L2=0
    devices:
      - /dev/video0:/dev/video0
    cap_add:
      - SYS_ADMIN
    privileged: true
    tty: true
    stdin_open: true

  frontend:
    container_name: frontend
    image: substobeme/spe_project:frontend
    ports:
      - "5002:5002"
    volumes:
      - ./db:/app/db
      - ./models:/app/models
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - recognition
    command: python app.py
