apiVersion: v1
kind: Pod
metadata:
  name: copy-models
  namespace: face-recognition
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: models
      mountPath: /app/models
  volumes:
  - name: models
    persistentVolumeClaim:
      claimName: models-pvc
