apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: face-recognition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: face-recognition:latest
        command: ["/bin/bash"]
        args:
        - -c
        - |
          cd /app
          python app.py --host 0.0.0.0 --port 5002
        ports:
        - containerPort: 5002
        env:
        - name: FLASK_APP
          value: "app.py"
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_DEBUG
          value: "1"