# PVC for models directory (encodings.pkl)
# PVC for models directory (encodings.pkl)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: face-recognition
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Add this line
---
# PVC for database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: face-recognition
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# PVC for data directory (face images)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: face-recognition
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi