# k8s/recognition-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recognition
  namespace: face-recognition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recognition
  template:
    metadata:
      labels:
        app: recognition
    spec:
      containers:
      - name: recognition
        image: recognition:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: face-recognition-config
        volumeMounts:
        - name: models-volume
          mountPath: /app/models
        - name: data-volume
          mountPath: /app/data
        - name: db-volume
          mountPath: /app/db
        - name: x11-socket
          mountPath: /tmp/.X11-unix
        - name: video-device
          mountPath: /dev/video0
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: db-volume
        persistentVolumeClaim:
          claimName: db-pvc
      - name: x11-socket
        hostPath:
          path: /tmp/.X11-unix
      - name: video-device
        hostPath:
          path: /dev/video0