apiVersion: v1
kind: Service
metadata:
  name: recognition
  namespace: face-recognition
spec:
  selector:
    app: recognition
  ports:
  - port: 5002
    targetPort: 5002
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: face-recognition
spec:
  type: NodePort  # This will expose the service on a node port
  ports:
  - port: 5002
    targetPort: 5002
    nodePort: 30002  # This will be the port you access from your browser
  selector:
    app: frontend