# k8s/training-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training
  namespace: face-recognition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: training
        image: training:latest
        imagePullPolicy: Never
        command: ["python", "train_service.py"]
        volumeMounts:
        - name: models-volume
          mountPath: /app/models
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc