- name: Create Prometheus config directory
  file:
    path: /opt/monitoring
    state: directory

- name: Copy Prometheus config
  copy:
    src: prometheus.yml
    dest: /opt/monitoring/prometheus.yml

- name: Run Prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    state: started
    restart_policy: always
    published_ports:
      - 9090:9090
    volumes:
      - /opt/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

- name: Run Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    restart_policy: always
    published_ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana

- name: Run Node Exporter
  docker_container:
    name: node_exporter
    image: prom/node-exporter
    state: started
    published_ports:
      - 9100:9100

- name: Run cAdvisor
  docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    state: started
    published_ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
